AllCops:
  NewCops: enable
  Exclude:
    - 'spec/*'
    - 'spec/*/*'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/MethodLength:
  Max: 25

Layout/LineLength:
  Max: 150

Metrics/AbcSize:
  Max: 50

Layout/EndOfLine:
  EnforcedStyle: lf
  Enabled: False